version: '3'
services:
  spark:
    image: bitnami/spark:latest
    container_name: spark-master
    volumes:
      - ./dataflint.jar:/opt/spark/jars/dataflint.jar
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_PLUGINS=io.dataflint.spark.SparkDataflintPlugin
      - SPARK_EXTRA_CLASSPATH=/opt/spark/jars/dataflint.jar
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    volumes:
      - ./dataflint.jar:/opt/spark/jars/dataflint.jar
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_PLUGINS=io.dataflint.spark.SparkDataflintPlugin
      - SPARK_EXTRA_CLASSPATH=/opt/spark/jars/dataflint.jar
    depends_on:
      - spark
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
