global:
  scrape_interval: 5s  # Collect metrics every 5 seconds

scrape_configs:
  - job_name: 'spark'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['spark-master:8080', 'spark-worker:8080']

  - job_name: 'dataflint'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['spark-master:4040']
